export const SET_FILTERS = "SET_FILTERS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_ALERTS = "SET_ALERTS";
export const SET_ALERT_LEVELS = "SET_ALERT_LEVELS";
export const SET_NODE_IS_COLLAPSED = "SET_NODE_IS_COLLAPSED";
export const SET_ACTIVE_ALERTS_ONLY = "SET_ACTIVE_ALERTS_ONLY";